# Generated by Django 5.2.7 on 2025-10-24 13:12

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_signup_signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceDocument',
            fields=[
                ('id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_signup_signin.student')),
            ],
        ),
    ]
