# Generated by Django 5.2.7 on 2025-10-24 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancedocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
