# Generated by Django 5.2.6 on 2025-11-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDashboard', '0002_alter_clearancedocument_id'),
        ('student_signup_signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancedocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_documents', to='student_signup_signin.student'),
        ),
    ]
