# Generated by Django 5.2.7 on 2025-10-24 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid school email address.')])),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('library', 'Library'), ('accounting', 'Accounting'), ('acadaffairs', 'Academic Affairs'), ('studaffairs', 'Student Affairs'), ('itDepartment', 'IT Department'), ('plant', 'Physical Plant')], max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
