# Generated by Django 5.2.6 on 2025-11-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_hours', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notify_new_submissions', models.BooleanField(default=False)),
                ('urgent_alerts', models.BooleanField(default=False)),
                ('daily_summary', models.BooleanField(default=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='Faculty.faculty')),
            ],
        ),
    ]
