# Generated by Django 5.2.6 on 2025-11-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_departmentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('Library', 'Librarian'), ('Registrar', 'Registrar'), ('Finance Office', 'Finance Office'), ('Guidance Office', 'Guidance Office')], max_length=50),
        ),
    ]
