# Generated by Django 5.2.6 on 2025-11-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_alter_faculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('Library', 'Librarian'), ('Registrar', 'Registrar'), ('Accounting', 'Accounting'), ('Academic Adviser', 'Academic Adviser')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
